### ISSUE TITLE
pickle generates an error when running on python 3.7

### ISSUE THREAD

**Issue by hypsiche** [eparsonnet93/ekpmeasure#32]
`analysis.load_Dataset('dir')` creates the error `ValueError: unsupported pickle protocol: 5` when running with python 3.7. I would guess because pickle 5 starts in 3.8.

**Comment by eparsonnet93** [comment]
I've had problems with the pickling issue before. For all versions >=0.1.11 I will replace meta data files with .csvs only. I will close this issue once I publish v0.1.11 to pypi, though the code on the repo is updated with this fix already.

**Comment by eparsonnet93** [comment]
Updated. Closing this issue. Default is now to handle meta_data as csv's not pickles.  There may be persistent issues with `dataset.to_ekpds()`, if this happens, please let me know.
